### PR TITLE
Update build to use git commit instead of svn revision.

### PR DESCRIPTION
**Pull request by jawalonoski**
Changes the build to use the git commit hash instead of the svn revision number.

For example:

```
    [java] Full Build                                                                 0.901   4sec   95MB
    [java] Version 3.5.0-4b6f35af3b
```

### CODE REVIEW

**Comment by jawalonoski** [comment]
I think you still can using the now-misnamed `-svn` command line option.

**Comment by jawalonoski** [comment]
See conversation here: https://chat.fhir.org/#narrow/stream/9-committers/topic/Transition.20to.20GitHub

**Comment by grahamegrieve** [comment]
> I'd really rather see this passed in as an argument.

So anyone running the build has to figure out the argument value?

**Comment by grahamegrieve** [comment]
I'm going to close this - I picked up the code and moved into a much more extensive set of changes around this where I hunted down the consequences.

**Pull request closed without merging**
