### PR TITLE
Security sep23

### PR DESCRIPTION
**Pull request by JohnMoehrke**
## HL7 FHIR Pull Request

- FHIR-41877
- FHIR-42757

## Description

- fix DICOM mapping on EventId and EventTypeCode
- add break-glass using OAuth

### CODE REVIEW

**Comment by JohnMoehrke** [comment]
@lmckenzi please approve

**Review by lmckenzi — CHANGES_REQUESTED** [review]
There are a few hyperlinks that look like this:
http://www.hl7.org/search/viewSearchResult.cfm?search_id=393442&amp;search_result_url=%2Fdocumentcenter%2Fpublic%2Fwg%2Fsecure%2FHL7%20Emergency%20Access%2Edoc"

I think they should be the URLs for the documents, not the search results.

**Comment by JohnMoehrke** [comment]
> There are a few hyperlinks that look like this: http://www.hl7.org/search/viewSearchResult.cfm?search_id=393442&amp;search_result_url=%2Fdocumentcenter%2Fpublic%2Fwg%2Fsecure%2FHL7%20Emergency%20Access%2Edoc"
> 
> I think they should be the URLs for the documents, not the search results.

those have been in the spec all along like that, and it does work. But I will see what I can find.

**Comment by JohnMoehrke** [comment]
@lmckenzi please approve now with no link to that paper, as I could not find a formal HL7 publication, so I just wrote a paragraph.

**Review by lmckenzi — APPROVED** [review]

**Pull request merged**
