### PR TITLE
OO Updates

### PR DESCRIPTION
**Pull request by costateixeira**
## HL7 FHIR Pull Request

_Note: No pull requests will be accepted against `./source` unless logged in the_ [HL7 Jira issue tracker](https://jira.hl7.org/projects/FHIR/issues/).

If you made changes to any files within `./source` please indicate the Jira tracker number this pull request is associated with: `   `

## Description

_Please describe your pull request here._

### CODE REVIEW

**Review by rhausam — APPROVED** [review]
There is a lot of detail here (not a bad thing).  I believe the changes look to be correct and can be merged.  I will note that now the the data type has been changed to CodeableConcept and the binding is extensible rather than required, the short description for Device.name.type should no longer be an enumerated list of the codes.  Instead it should be changed to a meaningful (short) description of the meaning/purpose of the element.

**Comment by rhausam** [comment]
There is a build failure.  Unfortunately, I don't have time available now prior to the Connectathon to further investigate this.  First I think we need to be sure that a local build of this branch is in fact completing successfully.

**Comment by costateixeira** [comment]
apologies, this was a check I hadn't done (the short description for the
required binding must match the actual values).
I fixed this. The build is now working

**Comment by rhausam** [comment]
I was able to merge this on my phone GH app.

**Pull request merged**
