### PR TITLE
fixes for imaging resources

### PR DESCRIPTION
**Pull request by JohnMoehrke**
## HL7 FHIR Pull Request

- FHIR-43115
- FHIR-42742
- FHIR-39614

## Description

- fixes to ImagingSelectiona nd ImagingStudy
- alignment with FiveWs and Workflow

### CODE REVIEW

**Comment by JohnMoehrke** [comment]
Hold on approval/merge until the search parameter vs oid is resolved as either not needed or fixed.

**Comment by JohnMoehrke** [comment]
@jcwhitby Please review for the following things specifically
1. This build does not have a search parameter for ImagingStudy.series.instance.sopClass. This seems due to an incorrect fhir core build rule forbidding any kind of search against oid
2. I added some elements to the examples that are needed because we have search parameters and there must be at least one example with that element populated. (This could also be done by adding more examples)
3. I updated some Event workflow mapping, and FiveWs mapping to align with the new requirements.
4. On the new Event and FiveWs mapping requirements, you will now find files *-exceptions.xml" that are managed with the publisher to show when the resource deviates from these patterns. I have updated the non-mapped problems by populating the *reason*. 
5. I did NOT change any of the element descriptions to align with these patterns, so there are many deviations in these *-exceptions.xml files. These need to be resolved either by updating the element descriptions to perfectly align, or by adding a *reason* that indicates why each deviation is proper (for example in DocumentReference I indicated that some needed to deviate due to the resource use-case needs).

**Comment by JohnMoehrke** [comment]
CI build https://build.fhir.org/branches/moehrke-imaging-202312/

**Comment by JohnMoehrke** [comment]
asking @grahamegrieve for help on the uri/oid search parameter problem 
https://chat.fhir.org/#narrow/stream/179165-committers/topic/search.20on.20OID

**Review by grahamegrieve — APPROVED** [review]
ok

**Pull request merged**
