### PR TITLE
J#46538 Flag.status min

### PR DESCRIPTION
**Pull request by michelle-m-miller**
## Description

J#46538 Flag.status min = 0 (due to no unknown in value set)

### CODE REVIEW

**Review by lmckenzi — COMMENTED** [review]
Should there not be a comment explaining what implementers should infer if the status is missing?  Does it mean 'unknown'?

**Comment by michelle-m-miller** [comment]
> Should there not be a comment explaining what implementers should infer if the status is missing? Does it mean 'unknown'?

Do you mean adding a "meaningWhenMissing"?  If so, then Patient Care agrees to add "When status is not valued, it means the status is unknown."

**Comment by lmckenzi** [comment]
That would be great

**Review by grahamegrieve — APPROVED** [review]
ok

**Pull request merged**
