### PR TITLE
FHIR-40567 renaming MolSeq.formatted to MolSeq.file

### PR DESCRIPTION
**Pull request by khalifa-aly**
Based on FHIR-40567 and Clinical Genomics IM discussion, it was decided to rename MolSeq.formmated to MolSeq.file.

## HL7 FHIR Pull Request

_Note: No pull requests will be accepted against `./source` unless logged in the_ [HL7 Jira issue tracker](https://jira.hl7.org/projects/FHIR/issues/).

If you made changes to any files within `./source` please indicate the Jira tracker number this pull request is associated with: `   `

## Description

Based on FHIR-40567, MolSeq.formatted element was renamed to MolSeq.file.

### CODE REVIEW

**Review by sirkyp — COMMENTED** [review]
@khalifa-aly - did we have examples that use this attribute and also need to be changed?

**Comment by sirkyp** [comment]
@khalifa-aly - I think we have documentation that references the attribute name as well?

**Comment by khalifa-aly** [comment]
@sirkyp thanks for highlighting this. Would you please check the new edits?

**Comment by sirkyp** [comment]
Looks good to me @khalifa-aly

**Review by grahamegrieve — APPROVED** [review]
ok

**Pull request merged**
