### PR TITLE
Imaging selection Updates

### PR DESCRIPTION
**Pull request by canon-cmi-jonathan-whitby**
## HL7 FHIR Pull Request
ImagingSelection resource updates approved by Imaging Integration WG.

Associated Jira items: 
* FHIR-36648, FHIR-36649, FHIR-37408, FHIR-37409, FHIR-37411, FHIR-37683 (https://github.com/HL7/fhir/commit/5c5a620527e102650cad53df57ff594d1706fe2a)
* FHIR-37642 (https://github.com/HL7/fhir/commit/8fb6060e9937bb354a2b24d4c058ad266469f06e)

## Description
ImagingSelection updates:
* Maturity to 1
* Updated Scope and Usage based on DICOM WG-06 review
* DICOM UIDs use id instead of oid to match ImagingStudy
* Make ImagingSelection frameList, observationUid, segmentList and roiList mutually exclusive
* Split 2D and 3D imageRegion elements -- one under instance (2D) and one at top level (3D)

## Note
I made these changes in my fork to be able to review updates and @JohnMoehrke suggested I just create the PR instead of having him re-apply the changes.

### CODE REVIEW

**Comment by JohnMoehrke** [comment]
@jcwhitby This is failing because there are warnings in ImagingSelection, and that is not allowed with FMM 1

WARNING @ ImagingSelection: A resource must have an 'entered in error' status (src = ResourceValidator)
INFORMATION @ ImagingSelection: RIM Mapping is required (src = ResourceValidator)
INFORMATION @ ImagingSelection: RIM Mapping is required (src = ResourceValidator)
INFORMATION @ ImagingSelection.instance.imageRegion.regionType: Name of child (regionType) overlaps with name of parent (imageRegion) (src = ResourceValidator)
INFORMATION @ ImagingSelection.imageRegion.regionType: Name of child (regionType) overlaps with name of parent (imageRegion) (src = ResourceValidator)
WARNING @ ImagingSelection: Search Parameter study-uid : uri type illegal for ImagingSelection.studyUid : id (id) (src = ResourceValidator)
ERROR @ ImagingSelection: Resource ImagingSelection (FMM=1) cannot have an FMM level >1 (1) if it has warnings (src = ResourceValidator)

**Comment by JohnMoehrke** [comment]
why did you change the .idea/misc.xml file?

**Comment by jcwhitby** [comment]
> why did you change the .idea/misc.xml file?
> why did you change the codeSystem and valueSet in patient?
I think I accidentally pulled in another change. I've reverted those and am adding ImagingSelection.status.

**Comment by JohnMoehrke** [comment]
not clear why your change did not resolve the warning on entered-in-error

**Comment by jcwhitby** [comment]
> not clear why your change did not resolve the warning on entered-in-error

From experience with other build systems I would guess the two commits were too close together and it didn't re-run the build tasks for the second. I don't know if it can be manually re-initiated by someone with more rights than I have.

**Comment by JohnMoehrke** [comment]
im building local. Ill let you know

**Comment by JohnMoehrke** [comment]
no. local build also fails with the entered in error

**Comment by JohnMoehrke** [comment]
I figured it out. Will try a push to your branch

**Review by JohnMoehrke — APPROVED** [review]
updates have happened. Good to go now.

**Pull request merged**
