### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by wardweistra**
## HL7 FHIR Pull Request

_Note: No pull requests will be accepted against `./source` unless logged in the_ [HL7 Jira issue tracker](https://jira.hl7.org/projects/FHIR/issues/).

If you made changes to any files within `./source` please indicate the Jira tracker number this pull request is associated with: `   `

## Description

Adding some badges to get community engagement.

### CODE REVIEW

**Comment by grahamegrieve** [comment]
Are these still good changes? why?

**Comment by wardweistra** [comment]
It's a suggestion to add two badges to ease community engagement for people finding the GitHub page of FHIR first:

- A link to the Zulip chat
- A link to the HL7 FHIR questions on StackOverflow, including indication of the amount of recent questions.

If this needs a tracker item first, please let me know. Thought it was a small, non-controversial improvement.

**Comment by grahamegrieve** [comment]
ok. added it slightly differently with some more links in a different commit

**Comment by wardweistra** [comment]
Lovely, thanks

**Pull request closed without merging**
