### PR TITLE
FHIR-44633 Remove MessageHeader.endpoint.target

### PR DESCRIPTION
**Pull request by ajuliansr**
## HL7 FHIR Pull Request

_Note: No pull requests will be accepted against `./source` unless logged in the_ [HL7 Jira issue tracker](https://jira.hl7.org/projects/FHIR/issues/).

If you made changes to any files within `./source` please indicate the Jira tracker number this pull request is associated with: `   `

## Description

Remove MessageHeader.endpoint.target per discussions on https://confluence.hl7.org/pages/viewpage.action?pageId=230557012
and https://jira.hl7.org/browse/FHIR-44633

### CODE REVIEW

**Review by lmckenzi — COMMENTED** [review]
Pretty sure links shouldn't be pointing to build.fhir.org?  Can you verify with Grahame what the proper process is here?

**Comment by ajuliansr** [comment]
To which links are you referring?

Anthony (Tony) Julian FHL7, MQF
IT Technical Specialist II
EIA Platform
Information Technology
E-mail: ***@***.******@***.***>
Mayo Clinic
 200 First Street S.W.
 Rochester, MN 55905
 www.mayoclinic.org<http://www.mayoclinic.org/>



From: Lloyd McKenzie ***@***.***>
Sent: Wednesday, April 10, 2024 3:29 PM
To: HL7/fhir ***@***.***>
Cc: Julian, Anthony J. ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [HL7/fhir] FHIR-44633 Remove MessageHeader.endpoint.target (PR #3062)


@lmckenzi commented on this pull request.

Pretty sure links shouldn't be pointing to build.fhir.org? Can you verify with Grahame what the proper process is here?

-

**Comment by ajuliansr** [comment]
I think I see it now in https://github.com/HL7/fhir/pull/3062/files#diff-0953f50fa721c41dc79972bfc02eff7ebb4a7a3d6048006e1ed4755efb9b39b9
Will correct, and resubmit

Anthony (Tony) Julian

**Comment by ajuliansr** [comment]
I will remove the file from the PR.  I never changed it.  
It must be generated somewhere, because after changing the reference to build.fhir.org to hl7.org/fhir, and executing the desktop publish, the file is the same as before I started.

**Comment by ajuliansr** [comment]
I tried to checkout the original from master, but git said is was the same.  Go Figure.
So I copied the text from the source on github into the file, and did desktop publish, then re-committed.

**Review by lmckenzi — APPROVED** [review]

**Comment by ajuliansr** [comment]
Merging FHIR-44633 Remove MessageHeader.endpoint.target

**Pull request merged**
