### PR TITLE
Patient Administration R6 approved changes - batch 2

### PR DESCRIPTION
**Pull request by brianpos**
FHIR-41559 RelatedPersons description and relationship to Patient (message was in 2 places)
FHIR-41397 Search Parameters for resource Appointment are marked as non-repeating
FHIR-41400 Minor QA with search parameters and narrative
FHIR-37361 Clarify intent of onlyCertainMatches, and consider onlySingleMatch option
FHIR-40880 Reapply clarification of onlyCertainMatches
FHIR-41244 Patient Multiple Birth Total (R5+)to include fetal losses
FHIR-34375 Add Qualification status attribute in Practitioner
FHIR-41782 HealthcareService - is a referral required
FHIR-39306 HealthcareServices is missing some example code sets - characteristics, Service Eligibility
FHIR-15627 Social and Health Services Eligibility

### CODE REVIEW

**Review by lmckenzi — COMMENTED** [review]
Organization.qualification.status - should this addition be flagged as STU?

**Comment by brianpos** [comment]
> Organization.qualification.status - should this addition be flagged as STU?

Do you mean the property, valueset or codesystem?

**Comment by lmckenzi** [comment]
I meant the property, but probably all 3

**Review by lmckenzi — APPROVED** [review]
Sorry, confused Organization and Observation.

**Pull request merged**
