### PR TITLE
Group Resource: Added all CanonicalResource elements and added two invariants, J# 41583

### PR DESCRIPTION
**Pull request by Khalid-Shahin**
Added two invariants to the Group Resource.

Added all elements from the CanonicalResource Interface to Group

- Added Group.version
- Added Group.versionAlgorithm[x]
- Added Group.title
- Added Group.experimental
- Added Group.date
- Added Group.publisher
- Added Group.contact
- Added Group.useContext
- Added Group.purpose
- Added Group.copyright
- Added Group.copyrightLabel
- Added Group.url
- Added Group.status and made it 0..1
- And added url and status to Group search parameters

- Added Group to status-codes.xml

- Changed the Group resource suppressed-message warning

### CODE REVIEW

**Review by lmckenzi — APPROVED** [review]

**Review by lmckenzi — APPROVED** [review]

**Comment by Khalid-Shahin** [comment]
The last few commits won't build, so some adjustments will be needed.
When I remove Group.url from the search parameters I get this warning: "WARNING @ Group: A resource that contains a url element must have a search parameter 'url' (src = ResourceValidator)"

Would this go away if I add Group to the existing canonicalresource-url search? And how do I do that?

I also just removed Group.status from the search parameters as well.

**Comment by lmckenzi** [comment]
You'll have to find the place where the canonical searches are defined - presumably in the canonical resource folder

**Comment by lmckenzi** [comment]
Note that you typically shouldn't commit until the build runs locally.

**Comment by Khalid-Shahin** [comment]
> You'll have to find the place where the canonical searches are defined - presumably in the canonical resource folder

I see bundle-CanonicalResource-search-params.xml

But it has this and I don't see a resource list to add Group.

  <entry>
    <resource>
      <SearchParameter>
        <id value="CanonicalResource-status"/>
        <extension url="http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status">
          <valueCode value="normative"/>
        </extension>
        <extension url="http://hl7.org/fhir/build/StructureDefinition/path">
          <valueString value="{{name}}.status"/>
        </extension>
        <url value="http://hl7.org/fhir/build/SearchParameter/CanonicalResource-status"/>
        <description value="The current status of the {{title}}"/>
        <code value="status"/>
        <type value="token"/>
        <expression value="{{name}}.status"/>
        <processingMode value="normal"/>
      </SearchParameter>
    </resource>
  </entry>

**Pull request merged**
