### PR TITLE
R6 Ballot 2 Subscription Changes

### PR DESCRIPTION
**Pull request by GinoCanessa**
## HL7 FHIR Pull Request

_Note: No pull requests will be accepted against `./source` unless logged in the_ [HL7 Jira issue tracker](https://jira.hl7.org/projects/FHIR/issues/).

If you made changes to any files within `./source` please indicate the Jira tracker number this pull request is associated with: `FHIR-46492`, `FHIR-46493`, and `FHIR-46495`.

## Description

Subscription-related R6 changes.  Each commit includes the ticket for changes and details about what was done.

### CODE REVIEW

**Review by lmckenzi — COMMENTED** [review]
You're committing multiple plantUML files, but only one new SVG committed and added to the publish.ini?

**Comment by GinoCanessa** [comment]
> You're committing multiple plantUML files, but only one new SVG committed and added to the publish.ini?

Yes - the other SVG files there did not have independent plantUML files and I thought that was a bad idea (noticed because I wanted to modify one).

**Review by lmckenzi — APPROVED** [review]

**Comment by grahamegrieve** [comment]
do these have Jira tasks?

**Comment by GinoCanessa** [comment]
> do these have Jira tasks?

Yes. Each commit lists the ticket and specific changes.

**Comment by GinoCanessa** [comment]
I added the tickets to the PR message as well.  With Lloyd already approving, I assume it is okay to merge?

**Pull request merged**
