### PR TITLE
Moehrke security 202406

### PR DESCRIPTION
**Pull request by JohnMoehrke**
## HL7 FHIR Pull Request

- FHIR-46143
- FHIR-46144
- FHIR-45446

## Description

- Prep Consent for ballot by cleaning up warnings and quality
- Prep Security for ballot by cleaning up warnings and quality
- don't use experimental on codeSystems not intended to be experimental
- valueSet on AuditEvent.entity.detail.type is not the right valueSet, the right one is audit-entity-detail-type

### CODE REVIEW

**Comment by JohnMoehrke** [comment]
build log https://dev.azure.com/fhir-pipelines/fhir-publisher/_build/results?buildId=18010

**Comment by JohnMoehrke** [comment]
> build log https://dev.azure.com/fhir-pipelines/fhir-publisher/_build/results?buildId=18010

fixed. I had accidently removed the Provenance sort order warning.

**Comment by JohnMoehrke** [comment]
failed build log https://dev.azure.com/fhir-pipelines/fhir-publisher/_build/results?buildId=18016

**Comment by JohnMoehrke** [comment]
@grahamegrieve please review and approve this PR. It includes a change to oids.ini.

Note that I struggled for a very long time trying to figure out the following

```
Type error at char 1 in xsl:apply-templates/@select on line 14 column 70 
  XTTE0570: An empty sequence is not allowed as the value of variable $groups
  in global variable $groups (#13)
Error 
  SXXP0003: Error reported by XML parser: Premature end of file.
ERROR @ sec:ValueSet[audit-entity-detail-type].compose.include[1]: The system 'http://hl7.org/fhir/audit-entity-detail-type-sample' is not valid
```

only to find that the reason was that I had named the codeSystem being included with the word "sample" in it. When I renamed that codesystem without "sample" the build succeeded.

**Review by lmckenzi — APPROVED** [review]

**Pull request merged**
