### PR TITLE
J# 41583 changing order of elements for Group resource

### PR DESCRIPTION
**Pull request by Khalid-Shahin**
- Group element order now matches the CanonicalResource order.
- Removed Group.active.
- Updated the Group examples to match the Group element changes.
- Updated the Group UML diagram so that the elements aren't overlapping.

### CODE REVIEW

**Review by lmckenzi — CHANGES_REQUESTED** [review]
publisher, contact, etc. need to appear right after 'date'.  The order of all elements in a canonicalResource need to be consistent.  The resource-specific content should appear after copyrightLabel.

Also, 'active' should go away.  It's supplanted by 'status'.

**Comment by Khalid-Shahin** [comment]
Does this order of elements work?

**Comment by lmckenzi** [comment]
name, title and description need to be moved up.  All of the canonical elements must appear first in standard order.  Group-specific elements follow those.

**Comment by Khalid-Shahin** [comment]
> name, title and description need to be moved up. All of the canonical elements must appear first in standard order. Group-specific elements follow those.

I can't move the name element any higher than where it is without making it a breaking change since previously name appeared below code. And there is an example that won't compile without reordering the elements. Should I make the breaking change?

**Comment by lmckenzi** [comment]
Are none of the other changes breaking

**Comment by Khalid-Shahin** [comment]
> Are none of the other changes breaking

The only breaking change is the removal of Group.active.

**Comment by lmckenzi** [comment]
That's enough to make the update breaking.  Let's align the order completely.

**Comment by Khalid-Shahin** [comment]
> That's enough to make the update breaking. Let's align the order completely.

Made a commit so the elements match the CanonicalResource. Changed the examples to that change. The UML diagram is also fixed for the Group resource because before the element boxes were overlapping.

**Review by lmckenzi — APPROVED** [review]

**Pull request merged**
