### PR TITLE
Cg im molseq work in progress 2

### PR DESCRIPTION
**Pull request by khalifa-aly**
## HL7 FHIR Pull Request

_Note: No pull requests will be accepted against `./source` unless logged in the_ [HL7 Jira issue tracker](https://jira.hl7.org/projects/FHIR/issues/).

If you made changes to any files within `./source` please indicate the Jira tracker number this pull request is associated with: `   `

## Description

Updating Molecular Sequence resource to be definitional and how it represent sequences using various approaches.

### CODE REVIEW

**Review by lmckenzi — CHANGES_REQUESTED** [review]
It looks like compartments.xml didn't get normalized before being committed?  (Or it could be it wasn't normalized by whoever committed before you...)  Can you run a local build and see if that file changes, and if so, commit it to the branch?

**Comment by khalifa-aly** [comment]
I ran a local build, compartment.xml has not changes, and I got a build errors, below:
ERROR @ MolecularSequence: Resource MolecularSequence in compartment patient: parameter subject was not found (subject) (src = ResourceValidator)
ERROR @ compartment.patient.MolecularSequence.subject: Search Parameter 'subject' not found (src = ResourceValidator)

I commented out the subject cell from the relevant MolecularSequence row, re-ran the build and I got a successful build.
I commented this change and the Azure pipeline ran successfully.

**Comment by lmckenzi** [comment]
There's now a commented row in compartments.xml.  compartments.xml is a spreadsheet, so it shouldn't have comments...

**Comment by khalifa-aly** [comment]
> There's now a commented row in compartments.xml. compartments.xml is a spreadsheet, so it shouldn't have comments...

I've removed the commented out line.

**Comment by khalifa-aly** [comment]
CG IM is working on Molecular Definition resource and profiles that would replace MolSeq.

**Pull request closed without merging**
