### PR TITLE
removing old ClinicalUseIssue

### PR DESCRIPTION
**Pull request by riksmithies**
## HL7 FHIR Pull Request

_Note: No pull requests will be accepted against `./source` unless logged in the_ [HL7 Jira issue tracker](https://jira.hl7.org/projects/FHIR/issues/).

If you made changes to any files within `./source` please indicate the Jira tracker number this pull request is associated with: `   `

## Description

_Please describe your pull request here._

### CODE REVIEW

**Comment by grahamegrieve** [comment]
why is this a conflict?

**Comment by riksmithies** [comment]
I don't know and I don't know how to fix it. It builds ok locally. I'm starting again with another local build and will push it in stages this time. Then if that works I will delete this.

**Comment by grahamegrieve** [comment]
This shouldn't be necessary though - I have removed ClinicalUseIssue from R4B?

**Comment by riksmithies** [comment]
Ok great, thanks. I wasn't aware when I tried this. To get that resource to go away on my local build I had to rename a value set that the new reource name was using, referring to the old name (and so in the old name's folder, which I was trying to delete). So if that didn't happen in the build version it would explain the conflict. I will see if anything needs patching up.

**Pull request closed without merging**
