### PR TITLE
Bundle Profiles

### PR DESCRIPTION
**Pull request by bvdh**
## HL7 FHIR Pull Request

`https://jira.hl7.org/browse/FHIR-38943`

## Description

Added profiles for the main Bundle types

### CODE REVIEW

**Comment by bvdh** [comment]
The pull requests holds profiles for the main Bundle uses (document, batch, transaction, ...) and should reflect the restrictions on Bundle of each Bundle type. I would appreciate it if someone can take a look at them to make sure the modelling is correct.

**Comment by bvdh** [comment]
See discussion on https://chat.fhir.org/#narrow/stream/290243-FHIR-I.2Fcommitters/topic/Review.20requested.20for.20Bundle.20profiles

**Comment by grahamegrieve** [comment]
what is happening with this PR?

**Comment by bvdh** [comment]
Lloyd and I are working on the last topics.

Bas

**Pull request merged**
