### PR TITLE
Fix schemas

### PR DESCRIPTION
**Pull request by lmckenzi**
## HL7 FHIR Pull Request

_Note: No pull requests will be accepted against `./source` unless logged in the_ [HL7 FHIR gForge tracker](https://gforge.hl7.org/gf/project/fhir/tracker/?action=TrackerItemBrowse&tracker_id=677).

If you made changes to any files within `./source` please indicate the gForge tracker number this pull request is associated with: `   `

## Description

_Please describe your pull request here._

### CODE REVIEW

**Comment by grahamegrieve** [comment]
I don't understand these changes. Please explain

**Comment by grahamegrieve** [comment]
either of them - I don't understand why you are making them

**Comment by lmckenzi** [comment]
The declaration of the binding in ObservationDefinition spreadsheet caused AdministrativeGender to show up in the schema twice - which isn't allowed.  There's no need for ObservationDefinition to declare the binding because it's already a standard binding.

The FHIRVersion enumeration wasn't showing up in the schemas because the schema generation code only works from code lists, not from value sets.  I wasn't sure how to change the schema generation code to drive from value sets, so for now, I made it a code list.

**Comment by grahamegrieve** [comment]
the FHIRVersion thing - that has a long sting in the tail. you'll break other things downstream by making that change. I'll research that.

The line ending thing.. you set a value to it's default value... you haven't changed anything

**Comment by grahamegrieve** [comment]
and I wonder why broken schemas didn't break the build.. they are supposed to be checked

**Comment by lmckenzi** [comment]
In terms of the line ending piece, with the code change, I no longer see my generated version of snomed.xml and loinc.xml as having local changes to commit, so the default value was getting overridden somehow or other.  I'm not noticing a sting in the tail for the other change...

**Comment by lmckenzi** [comment]
When I ran the build without the change, I got a change in line endings.  When I ran it with the change, I got no change in line endings.  So something, somehow, was changing it.

**Comment by lmckenzi** [comment]
I ran the build before the change, reverted and ran the build after the
change.  I did not step through.

**Pull request merged**
