### PR TITLE
Fixes for Security December 2023

### PR DESCRIPTION
**Pull request by JohnMoehrke**
## HL7 FHIR Pull Request

- FHIR-42932
- FHIR-42797
- FHIR-41390
- FHIR-41262

## Description

- Rephrasing the AuditEvent description
- Provenance reason for change narrative
- Provenance support for group
- example data tagging with high-water mark
- address FiveWs mapping-exceptions
- address Event mapping-exceptions

### CODE REVIEW

**Comment by JohnMoehrke** [comment]
asking about multiple mapping to one element https://chat.fhir.org/#narrow/stream/179165-committers/topic/multiple.20mappings.20to.20one.20element

**Comment by JohnMoehrke** [comment]
asking about how to do baseOn request pattern mapping https://chat.fhir.org/#narrow/stream/179165-committers/topic/basedOn.20use.20of.20Request.20pattern

**Comment by JohnMoehrke** [comment]
CI build - https://build.fhir.org/branches/moehrke-security-202312/

**Comment by JohnMoehrke** [comment]
@grahamegrieve @lmckenzi -- should we accept this pull-request in and address the further refinement of the mapping exceptions in the future? I am waiting for you to either approve my pull-request, or provide solution that can help me make my pull-request better.

**Review by grahamegrieve — APPROVED** [review]
ok

**Pull request merged**
