### PR TITLE
Try, try again:

### PR DESCRIPTION
**Pull request by ajuliansr**
#FHIR-39096 Use Bundle.identifier to identify the logical message construct #FHIR-40518 There can be zero or more response messages #FHIR-40519 Wording on protocols is unclear

## HL7 FHIR Pull Request

_Note: No pull requests will be accepted against `./source` unless logged in the_ [HL7 Jira issue tracker](https://jira.hl7.org/projects/FHIR/issues/).

If you made changes to any files within `./source` please indicate the Jira tracker number this pull request is associated with: `   `

## Description

_Please describe your pull request here._
#FHIR-39096 Use Bundle.identifier to identify the logical message construct
#FHIR-40518 There can be zero or more response messages
#FHIR-40519 Wording on protocols is unclear

### CODE REVIEW

**Comment by vassilpeytchev** [comment]
@ajuliansr I think you may be out of sync with master. Let me pull in your changes, and try to build locally. `force-push` seems to be the wrong thing to do.

**Comment by vassilpeytchev** [comment]
FWIW, your changes include 
source/deviceassociation/codesystem-deviceassociation-operationstatus.xml 
 source/deviceassociation/structuredefinition-DeviceAssociation.xml
 source/deviceassociation/valueset-deviceassociation-operationstatus.xml

Was that intended?

**Comment by ajuliansr** [comment]
Would you like me to send the files

**Comment by vassilpeytchev** [comment]
I got them from your branch. I can finish with the Pull Request if you would like me to, in which case you can close this one.

**Comment by ajuliansr** [comment]
If you have the time, I would appreciate it.  Please explain "close this one"

**Comment by ajuliansr** [comment]
Do you mean just click on Close with Comment?

**Comment by vassilpeytchev** [comment]
Yes, "Close with Comment"

**Comment by ajuliansr** [comment]
Closing  - Vassil will complete.  I owe him !

**Comment by ajuliansr** [comment]
_I didnt change 
source/deviceassociation/codesystem-deviceassociation-operationstatus.xml
source/deviceassociation/structuredefinition-DeviceAssociation.xml
source/deviceassociation/valueset-deviceassociation-operationstatus.xml_

**Comment by ajuliansr** [comment]
I only staged/committed messageheader-notes.xml and messaging.html

**Comment by vassilpeytchev** [comment]
Yes, those were actually from master.

**Pull request closed without merging**
